config/routes.rb
Lions::Application.routes.draw do

  resources :predicts do
    collection { put :scores };
      collection {put :lock}
  end

  get 'scoreboards/summary', :to => "scoreboards#summary"
  resources :scoreboards do
    collection { post :generate }
  end

  get 'squad_performances/played', :to => "squad_performances#played"
  resources :squad_performances do
     collection { put :onfield };
       collection { post :generate }
   end

    get 'squads/test1', :to => "squads#test1"
        get 'squads/test2', :to => "squads#test2"
            get 'squads/test3', :to => "squads#test3"
  resources :squads

  get 'fixtures/calendar', :to => "fixtures#calendar"
  get 'fixtures/allpredicts', :to => "fixtures#allpredicts"
  
  resources :fixtures do
    collection { post :import }
  end

  resources :users
    resources :sessions, only: [:new, :create, :destroy]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

   
  resources :matchpicks   do
       collection { put :selected };
       collection { put :update};
       collection {put :scores};
        collection {put :choose};
          collection {put :lock}
  end

  resources :squads do
    collection { post :import }
  end

  root to: 'static_pages#home'

  match '/demo',   to: 'static_pages#demo'
  match '/home',   to: 'static_pages#home'
  match '/index',   to: 'static_pages#home'
  match '/',   to: 'static_pages#home'
  match '/admin',   to: 'static_pages#admin'
  match '/rules',   to: 'static_pages#rules'
  match '/welcome',   to: 'static_pages#welcome'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def admin
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_header.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Lions Tour 2013</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

   <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
 
							
 </head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/home">Lions '13</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            <li class="active"><a href="/fixtures">Fixtures</a></li>            
            <li class="active"><a href="/users">Users</a></li>
  			<li class="active"><a href="/matchpicks">Teams</a></li>
            <li class="active"><a href="/scoreboards">Results</a></li>
			<li class="active"><a href="/rules">Rules</a></li>
            <li class="active"><a href="/admin">Admin</a></li>
<% if signed_in? %>
           <li class="active"><a href="/users/<%= current_user.id %>">::<%= current_user.name %>::</a></li>
           <li class="active"><a href='/signout' rel="nofollow" data-method="delete" data-confirm="Are you sure?">| Sign Out |</a></li>
<% else %>
           <li class="active"><a href="/signin">| Sign In | </a></li>	
<% end %>
 			</ul>
          </div>
        </div>
      </div>
    </div>

app/views/static_pages/admin.html.erb
      <hr>
 		<h3><%= link_to 'Users', users_path %></h3>
 		<h3><%= link_to 'User Matchpicks', matchpicks_path %></h3>

      	<h3><%= link_to 'Squad', squads_path %></h3>
      	<h3><%= link_to 'Squad Performance', squad_performances_path %></h3>


<br>

      <div class="footer">
        <p>&copy; StepStoneWeb 2013</p>
      </div>

    </div>

  </body>
</html>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>2013 Lions Tour</h1>
  <p class="lead">yet another predictascore</p>
  
  	<% if signed_in? %>
  	  <img src="/images/lions_logo.png">
  	  <h4>Hello <strong><%= current_user.name %></strong>, could this be your lucky year? </h4>
  	  <% else %>
  <a class="btn btn-large btn-success" <%= link_to 'Sign up', new_user_path %> </a> or 
	<a class="btn btn-large btn-info" <%= link_to 'Sign in', signin_path %> </a>
	
</div>

<hr>

<div class="row-fluid marketing">
  <div class="span5 offset 1">
    <h4>Free to enter</h4>
    <p>No entries fees this time, £20 to the winner.</p>

    <h4>Enter scores online</h4>
    <p>Give up the napkins and postcards, enter your scores online.</p>
  </div>

  <div class="span5 offset1">
    <h4>View all predictions online</h4>
    <p>No more "I can't remember my predictions" on match day.</p>

    <h4>Results</h4>
    <p>Public display of humiliation.</p>

  </div>
</div>
<% end %>
<hr>

app/views/static_pages/orirules.html.erb
<h2>Rules</h2><br>
<ul>
<h3>Creating your Lions Test Match Squad</h3>
	<li>All competitors need to create a user profile to track their account.</li>
	<li>Each competitor must create their own Lions Test Match Squad containing 15 players.</li>
	<li>>> Players must be selected from backs and forwards, onsite guidance provided.</li>
	<li>Each competitor must <b>lock in</b> their selection, once completed, prior to the first test match. </li>
	<li>>> Once a competitor has locked their team they will be able to view other competitors locked in teams. </li>
	<li>>> Initial draft teams cannot be viewed by other competitors.</li>
	<li>Locked in teams cannot be altered, expect by the site administrator under special circumstances.</li><br>

<h3>Test Match Squad Scoring</h3>
	<li>Each competitor will receive 2 points for any player in their squad who starts a test match and 1 point for a player subbed in during the test match.</li>
	<li>2 extra points will be awarded if a player in a competitors squad scores a try or a drop goal in any match.</li>
	<li>No points to be awarded for kicked points other than drop goals.</li>
	<li>Points scored per match are available in the Leaderboard page.</li>
	<li>Scores will be updated after each test match.</li><br>
	
<h3>All Match Score Predictions</h3>
	<li>Each competitor will make match score predictions for each Lions tour matche.</li>
	<li>Predictions must be <b>locked in</b> before the first match (1st June 2013)
	<li><i> ***** Six Nations P score rules to apply to the match predictions.
</i>
	</li>
	</ul>
<br><br><br>

      <div class="footer">
        <p>&copy; StepStoneWeb 2013</p>
      </div>

    </div>

  </body>
</html>

app/views/static_pages/rules.html.erb
<h3>Help</h3><br>
<div class="row-fluid">
  <div class="span6 offset1">

<ul>
	<li>Sign up - create your account.</li>
	<li>Enter your scores online before 21st June.</li>
	<li>Standard 6 Nations Predictascore rules to be applied for points scoring.</li>
	<li>Results will be updated online asap after each game.</li>
	<li>The winner gets £20.</li>
</ul>	
<br>
<br>
</div></div>

app/views/static_pages/welcome.html.erb
	<br>
<% if signed_in? %>
Hi <b><%= current_user.name %></b>
<% else %>
Thanks for creating your account.
<% end %> <br><br>
<h2>Welcome to the Lions Tour competition</h2><br>
<br>

You have <strong>two</strong> more steps before your account is complete:<br>
<br>
<ul>
	<h3>1)  Before 1st June - Lock in your predictions for all the Lions tour matches.</h3><br>
	<h3>2)  Before 22nd June - Lock in your Lions test match team</h3><br>

</ul>
<br>

<a class="btn btn-large btn-info" <%= link_to 'Get Started >>', @current_user %> </a>

    </div> 

  </body>
</html>