config/routes.rb
Lions::Application.routes.draw do

  resources :predicts do
    collection { put :scores };
      collection {put :lock}
  end

  get 'scoreboards/summary', :to => "scoreboards#summary"
  resources :scoreboards do
    collection { post :generate }
  end

  get 'squad_performances/played', :to => "squad_performances#played"
  resources :squad_performances do
     collection { put :onfield };
       collection { post :generate }
   end

    get 'squads/test1', :to => "squads#test1"
        get 'squads/test2', :to => "squads#test2"
            get 'squads/test3', :to => "squads#test3"
  resources :squads

  get 'fixtures/calendar', :to => "fixtures#calendar"
  get 'fixtures/allpredicts', :to => "fixtures#allpredicts"
  
  resources :fixtures do
    collection { post :import }
  end

  resources :users
    resources :sessions, only: [:new, :create, :destroy]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

   
  resources :matchpicks   do
       collection { put :selected };
       collection { put :update};
       collection {put :scores};
        collection {put :choose};
          collection {put :lock}
  end

  resources :squads do
    collection { post :import }
  end

  root to: 'static_pages#home'

  match '/demo',   to: 'static_pages#demo'
  match '/home',   to: 'static_pages#home'
  match '/index',   to: 'static_pages#home'
  match '/',   to: 'static_pages#home'
  match '/admin',   to: 'static_pages#admin'
  match '/rules',   to: 'static_pages#rules'
  match '/welcome',   to: 'static_pages#welcome'

end

app/models/predict.rb
class Predict < ActiveRecord::Base
  attr_accessible :awayscore, :fixture_id, :homescore, :matchpick_id, :user_id
  
  
 
end

app/controllers/predicts_controller.rb
class PredictsController < ApplicationController
  # GET /predicts
  # GET /predicts.json
  def index
    @predicts = Predict.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @predicts }
    end
  end
  
  def scores
    @predicts = Predict.find(params[:id])
    for predict in @predicts
         if @predict.update_attributes(:homescore => (params[:home_predict]),:awayscore => (params[:away_predict]))
          end  
        end
          @user = User.find(params[:user_id])
   redirect_to user_path(@user)
  end
  
  
    
  def lock
     @matchpick = Matchpick.find(params[:matchpick_id])

     respond_to do |format|
       if @matchpick.update_attributes(:status => 'Locked')

         format.html { redirect_to predict_path(@matchpick) }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @matchpick.errors, status: :unprocessable_entity }
       end
     end
    end

  # GET /predicts/1
  # GET /predicts/1.json
  def show
    @predicts = Predict.where(params[:matchpick_id])
    @matchpick = Matchpick.find(params[:id])
 
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @predict }
    end
  end

  # GET /predicts/new
  # GET /predicts/new.json
  def new
    @predict = Predict.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @predict }
    end
  end

  # GET /predicts/1/edit
  def edit
    @predict = Predict.find(params[:id])
  end

  # POST /predicts
  # POST /predicts.json
  def create
    @predict = Predict.new(params[:predict])

    respond_to do |format|
      if @predict.save
        format.html { redirect_to @predict, notice: 'Predict was successfully created.' }
        format.json { render json: @predict, status: :created, location: @predict }
      else
        format.html { render action: "new" }
        format.json { render json: @predict.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /predicts/1
  # PUT /predicts/1.json
  def update
    @predict = Predict.find(params[:id])

    respond_to do |format|
      if @predict.update_attributes(params[:predict])
        format.html { redirect_to @predict, notice: 'Predict was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @predict.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predicts/1
  # DELETE /predicts/1.json
  def destroy
    @predict = Predict.find(params[:id])
    @predict.destroy

    respond_to do |format|
      format.html { redirect_to predicts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/predicts_helper.rb
module PredictsHelper
end

app/views/predicts/_form.html.erb
<%= simple_form_for(@predict) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fixture_id %>
    <%= f.input :user_id %>
    <%= f.input :homescore %>
    <%= f.input :awayscore %>
    <%= f.input :matchpick_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/predicts/_score.html.erb
<table>
	<tr>
		<th>Match No.</th>
		<th>Date</th>
		<th>Opponent</th>
		<th>Location</th>
		<th>Test</th>
		<th>Home Team</th>
		<th>Lions</th>
	</tr>
		<% @predicts = Predict.where(:matchpick_id => (params[:id])) %>

	<% for predict in @predicts do %>
	<tr>
			
		<% r = predict.fixture_id %>	
		<td><center><%= r %></td>
		<td><center><%= Fixture.find(r).match %></td>
		<td nowrap="nowrap"><%= Fixture.find(r).hometeam %></td>
		<td><center><%= Fixture.find(r).city %></td>
			<td><center><% fix = Fixture.find(r).test %><% unless fix.nil? %>
				<% if fix == true %>
				<i class='icon-ok'></i>
				<% else %>
			<% end %><% end %>
			</center></td>
					<td><center><%= predict.homescore %></td>
					<td><center><%= predict.awayscore   %></td>
	</tr>	
	<% end %>
	</table>

app/views/predicts/_scoreform.html.erb
<table>
	<tr>
		<th>Match No.</th>
		<th>Date</th>
		<th>Opponent</th>
		<th>Location</th>
		<th>Test</th>
		<th>Home Team</th>
		<th>Lions</th>
		<th></th>
	</tr>
	<tr><td></td><td></td><td></td><td></td>
		<td><i>* *save scores</i></td><td><i>one row at a </i></td><td><i>time * *</i></td></tr>

		<% @predicts = Predict.where(:matchpick_id => (params[:id])) %>

	<% for predict in @predicts do %>
	<tr>
			<% r = predict.fixture_id %>
			<td><center><%= r %></td>	
		<td><center><%= Fixture.find(r).match %></td>
		<td nowrap="nowrap"><%= Fixture.find(r).hometeam %></td>
		<td><%= Fixture.find(r).city %></td>
			<td><center><% fix = Fixture.find(r).test %><% unless fix.nil? %>
				<% if fix == true %>
				<i class='icon-ok'></i>
				<% else %>
			<% end %><% end %>
			</center></td>
					<%= form_tag scores_predicts_path, method: :put do %>
				<td>
						<%= number_field_tag "home_predict", params[:homescore], :value=>predict.homescore %>
						
						<%= hidden_field_tag "id", predict.id %>
						<%= hidden_field_tag "matchpick_id", params[:id] %>
								</td>
								<td><center><%= number_field_tag "away_predict", params[:awayscore], :value=>predict.awayscore   %></td>
								<td><% if predict.homescore > 0 %>
								<%= submit_tag "Edit score", class: "btn btn-info" %>
								<% else %>
								<%= submit_tag "Save score", class: "btn btn-success" %><% end %><% end %></td>
				
	</tr>	
<% end %>
	</table>

app/views/predicts/edit.html.erb
<h2>Edit prediction</h2>

<%= render 'form' %>

<%= link_to 'Show', @predict %> |
<%= link_to 'Back', predicts_path %>

app/views/predicts/index.html.erb
<h2>Predictions</h2>

<table>
  <tr>
    <th>Fixture</th>
    <th>User</th>
    <th>Homescore</th>
    <th>Awayscore</th>
    <th>Matchpick</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @predicts.each do |predict| %>
  <tr>
    <td><%= predict.fixture_id %></td>
    <td><%= predict.user_id %></td>
    <td><%= predict.homescore %></td>
    <td><%= predict.awayscore %></td>
    <td><%= predict.matchpick_id %></td>
    <td><%= link_to 'Show', predict %></td>
    <td><%= link_to 'Edit', edit_predict_path(predict) %></td>
    <td><%= link_to 'Destroy', predict, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Predict', new_predict_path %>

app/views/predicts/new.html.erb
<h2>New prediction</h2>

<%= render 'form' %>

<%= link_to 'Back', predicts_path %>

app/views/predicts/show.html.erb
<p id="notice"><%= notice %></p>

<% u = @matchpick.user_id %><% @user = User.find(u) %>
<h3>Score Predictions ::<%= @user.name %>::</h3><br>

	<div class="row">
	  <div class="span10">
	<% if @matchpick.status == "Locked" %>
	<%= render 'predicts/score' %>
	<% else %>
	<%= render 'predicts/scoreform' %>
	<% end %>

</div></div>
<br>
		<% r = @matchpick.user_id %><% @user = User.find(r) %>
		<% unless @matchpick.status == "Locked"%>
		<%= form_for @matchpick, :url => { :action => "lock" }, :html => {:class => "nifty_form"} do |f| %>
			<table class="table">
			<tr>
				<td><center>Your Team Status is:</td>
				<td>
						<div class="field">
						    <%= f.text_field :status, :disabled=>true%>
						</div>
		      			</div>
						<%= hidden_field_tag "matchpick_id", params[:id] %>
				</td>
				<td><center>Ready to lock your scores?</td>
				<td>
					<div class="actions">
		    		<%= f.submit "Lock Scores", class: "btn btn-danger"  %>
					</div>	<% end %>
				</td>
			</tr>
			</table>

			<% else %>
			<h3>Congratulations your scores are <%= @matchpick.status %> </h3><br>
			<% end %>
		
<br> <%= link_to 'Back to User Summary >>', @user %>