config/routes.rb
Lions::Application.routes.draw do

  resources :predicts do
    collection { put :scores };
      collection {put :lock}
  end

  get 'scoreboards/summary', :to => "scoreboards#summary"
  resources :scoreboards do
    collection { post :generate }
  end

  get 'squad_performances/played', :to => "squad_performances#played"
  resources :squad_performances do
     collection { put :onfield };
       collection { post :generate }
   end

    get 'squads/test1', :to => "squads#test1"
        get 'squads/test2', :to => "squads#test2"
            get 'squads/test3', :to => "squads#test3"
  resources :squads

  get 'fixtures/calendar', :to => "fixtures#calendar"
  get 'fixtures/allpredicts', :to => "fixtures#allpredicts"
  
  resources :fixtures do
    collection { post :import }
  end

  resources :users
    resources :sessions, only: [:new, :create, :destroy]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

   
  resources :matchpicks   do
       collection { put :selected };
       collection { put :update};
       collection {put :scores};
        collection {put :choose};
          collection {put :lock}
  end

  resources :squads do
    collection { post :import }
  end

  root to: 'static_pages#home'

  match '/demo',   to: 'static_pages#demo'
  match '/home',   to: 'static_pages#home'
  match '/index',   to: 'static_pages#home'
  match '/',   to: 'static_pages#home'
  match '/admin',   to: 'static_pages#admin'
  match '/rules',   to: 'static_pages#rules'
  match '/welcome',   to: 'static_pages#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :email, :name, :password, :password_confirmation, :password_digest, :remember_token, :matchpicks_attributes
  has_many :matchpicks
  has_secure_password
  accepts_nested_attributes_for :matchpicks, allow_destroy: true
  
  validates :name, presence: true, length: { maximum: 30 },
                    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates :password_confirmation, presence: true
                    
  before_save :create_remember_token
  after_create :create_squad
  after_create :create_scores
  
  private
  def create_squad
    u = self.id
      m = Matchpick.new(:status => "Initial", :reason => "Team", :choose => "Select..", :user_id => u)
        m.save
    @squadids = Squad.pluck(:id)
    
    i = 0
      x = Squad.count
     
      while i < x do
          s = Playerpick.new(:matchpick_id => m.id, :squad_id => @squadids[i], :selected => false)
          s.save
          i = i += 1
      end
  end

  def create_scores
    u = self.id
      m = Matchpick.new(:status => "Initial", :reason => "Scores", :user_id => u)
        m.save
    @fixtureids = Fixture.where(:test => true).collect {|r| r.id}
    
    i = 0
      x = @fixtureids.count
     
      while i < x do
          s = Predict.new(:matchpick_id => m.id, :fixture_id => @fixtureids[i])
          s.save
          i = i += 1
      end
  end

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :correct_user,   only: [:show, :edit, :update]
  before_filter :admin_user,     only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

        if @user.save
          sign_in @user
            # Tell the UserMailer to send a welcome Email after save
            # UserMailer.welcome_email(@user).deliver
                  
          redirect_to @user, notice: "Thanks for creating your account."
        else
          render 'new'
        end
    
      end
    

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
            sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
   private

      def signed_in_user
        redirect_to signin_url, notice: "Please sign in." unless signed_in?
      end

      
      def correct_user
         @user = User.find(params[:id])
         redirect_to(root_path) unless current_user?(@user) or current_user.admin? 
         
      end

      def admin_user
            redirect_to(root_path) unless current_user.admin?
      end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="span6 offset3">

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>
	  
	<%= f.label :password_confirmation, "Password Confirmation" %>
	<%= f.password_field :password_confirmation %><br>
	
		<% if current_user.name == "pethl" %>
		<%= f.label :admin %>
		<%= f.check_box :admin %><br>
		<% else %>
		<% end %>

<i> Password/confirmation must be re-entered <br>prior to updating profile info. <i><br><br>
				<div class="actions">
				    <%= f.submit "Update User Profile", class: "btn btn-success"  %>
					</div>
						
<% end %>

app/views/users/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/users/_matchpick_fields.html.erb
<div>
<fieldset>
<table class="table">

	<tr>
		<td><b> Team Status   </b></td>
		<td><div class="field">
		    <%= f.select(:status, Matchpick::PICK_TYPES)%>
		  </div>
		</td>
	</tr>
	<tr>
		<i>Make your Test match team selection by selecting the checkbox next to a players name.<br>
			You can save your selections before locking in your team and return to it later.<br>
			When you are happy with you team selection, change <b>Team Status</b> to <b>Locked</b>.<br>
			Once Locked, your team cannot be changed, but you can view other users' Locked team selections.</i>
	</tr>

	
<!-- might need this later under admin, but currently the regeneration of the team doesn't work on create matchpick so dont use til fixed
  <%= f.check_box :_destroy %><%= f.label :_destroy, "Drop team and start again" %><br>
-->
  
<%= f.fields_for :playerpicks do |builder| %>
    <%= render 'playerpick_fields', f: builder %>
  <% end %>
 
<!-- put this under admin function only 
 <%= link_to_add_fields "Add Player Picks", f, :playerpicks %>
-->

</fieldset>
</div>

app/views/users/_playerpick_fields.html.erb
<div>


<table class="table">
<tr>
<td>

  <%= f.text_field :squad_id %>
 


</td>
<td>
  <%= f.check_box :selected %><br><br>
</td>
</tr>
</table>
</div>

app/views/users/edit.html.erb
<h3>User Profile ::<%= @user.name %>::</h3><br>

<%= render 'form' %>

<%= link_to 'Back to Profile >>', @user %>
</div></div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="row-fluid">
  <div class="span6 offset1">

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th><center>Created</center></th>

	<th>Admin</th>
	<th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %> </td>
    <td><%= user.email %></td>
   			 <td><%= user.created_at %></td>
				   <td><%= user.admin %></td>
	<td><%= link_to 'edit', edit_user_path(user) %> | <%= link_to 'destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Sign up', new_user_path, class: "btn btn-primary" %>
<%= link_to 'Sign in', signin_path, class: "btn btn-primary" %>
</div></div>

app/views/users/new.html.erb
<h2>Sign up</h2><br>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="span6 offset3">


	<%= f.label :name %>
	<%= f.text_field :name %>
  

	<%= f.label :email %>
	<%= f.text_field :email %>
   

	<%= f.label :password %>
	<%= f.password_field :password %>
	  

	<%= f.label :password_confirmation, "Please re-enter your password" %>
	<%= f.password_field :password_confirmation %>
	 
	
			</table>
			<div class="actions">
				 <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>
				</div>
					</div>
						</div>
<% end %>

<%= link_to 'Back', :home %>

app/views/users/show.html.erb
<% require 'date' %>
<% date = DateTime.parse("2013-06-22 00:00:00") %>
	
<h3>Hello <%= @user.name %></h3><br>

<div class="row">
  <div class="span5 offset1">
	<h4>Lions Test Match Predictions </h4>
	<% if date > Date.today %> 
			<p>	Enter your scores, then take a look around the site.<br>
			You will be able to see other user predictions from 22nd June.
			 </p>
			<% else %>
			See all other user predictions <%= link_to 'here >>', fixtures_allpredicts_path %><br>
			<% end %>
	
	<div class="well well-small">

  <table>	
	<tr>
	<th></th>
	<th>Australia</th>
	<th>Lions</th>
	<th></th>
	</tr>
	
	<% if @user.matchpicks.where(:reason => "Scores").any? %>
		<% for matchpick in @user.matchpicks %>
			
		<% @predicts = Predict.where(:matchpick_id => matchpick.id).order(:id) %>
		
				<% for predict in @predicts do %>
					<% r = predict.fixture_id %>
			<tr>
			<td><center><%= Fixture.find(r).match %><br><strong><%= Fixture.find(r).city %></strong>
			</td> 
			  <% if date > Date.today %> 
			  <td><center><%= best_in_place predict, :homescore, :nil => "Click to enter" %></center></td>
			  <td><center><%= best_in_place predict, :awayscore, :nil => "Click to enter" %></center></td>
        <% else %>
        <td><center><%= predict.homescore %></center></td>
			  <td><center><%= predict.awayscore %></center></td>
        <% end %>
        <td><% if date < Date.today %> 
  					<p>	<center><i class="icon-lock"></i><center> </p>
  					<% else %>
  					<% end %>
  						</td>

        <% end %>
        <% end %>
        <% end %>
					</tr>
					</table>					
		      </div> 
		      
		      	<% if  date > Date.today %>
        			<i>Scores will lock at midnight GMT on 21st June<i>
        				<% else %>
        					<% end %><br></div>
			</div> <br>
			

app/views/users/spooky.html.erb
Spooky