config/routes.rb
Lions::Application.routes.draw do

  resources :predicts do
    collection { put :scores };
      collection {put :lock}
  end

  get 'scoreboards/summary', :to => "scoreboards#summary"
  resources :scoreboards do
    collection { post :generate }
  end

  get 'squad_performances/played', :to => "squad_performances#played"
  resources :squad_performances do
     collection { put :onfield };
       collection { post :generate }
   end

    get 'squads/test1', :to => "squads#test1"
        get 'squads/test2', :to => "squads#test2"
            get 'squads/test3', :to => "squads#test3"
  resources :squads

  get 'fixtures/calendar', :to => "fixtures#calendar"
  get 'fixtures/allpredicts', :to => "fixtures#allpredicts"
  
  resources :fixtures do
    collection { post :import }
  end

  resources :users
    resources :sessions, only: [:new, :create, :destroy]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

   
  resources :matchpicks   do
       collection { put :selected };
       collection { put :update};
       collection {put :scores};
        collection {put :choose};
          collection {put :lock}
  end

  resources :squads do
    collection { post :import }
  end

  root to: 'static_pages#home'

  match '/demo',   to: 'static_pages#demo'
  match '/home',   to: 'static_pages#home'
  match '/index',   to: 'static_pages#home'
  match '/',   to: 'static_pages#home'
  match '/admin',   to: 'static_pages#admin'
  match '/rules',   to: 'static_pages#rules'
  match '/welcome',   to: 'static_pages#welcome'

end

app/models/squad.rb
class Squad < ActiveRecord::Base
  attr_accessible :age, :country, :group, :height, :name, :position, :position_strg, :weight, :test1, :test2, :test3
  
   validates_presence_of :name
   validates :group, presence: true
   validates :position, presence: true
  

     default_scope order: 'squads.position ASC'

     def self.import(file)
       CSV.foreach(file.path, headers: true) do |row|
        Squad.create! row.to_hash
    end
  end
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  respond_to :html, :json
  
  # GET /squads
  # GET /squads.json
  def index
    @squads = Squad.all
    @squad_by_group = @squads.group_by(&:group) 
    @squad_by_country = @squads.group_by(&:country) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @squads }
    end
  end
  
  def test1
    @squads_test1 = Squad.where(:test1 => true)
  end
  
  def test2
    @squads_test2 = Squad.where(:test2 => true)
  end
  
  def test3
    @squads_test3 = Squad.where(:test3 => true)
  end

  def import
      Squad.import(params[:file])
      redirect_to squads_path, notice: "Squad imported."
    end

  # GET /squads/1
  # GET /squads/1.json
  def show
    @squad = Squad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @squad }
    end
  end

  # GET /squads/new
  # GET /squads/new.json
  def new
    @squad = Squad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @squad }
    end
  end

  # GET /squads/1/edit
  def edit
    @squad = Squad.find(params[:id])
  end

  # POST /squads
  # POST /squads.json
  def create
    @squad = Squad.new(params[:squad])

    respond_to do |format|
      if @squad.save
        format.html { redirect_to @squad, notice: 'Squad was successfully created.' }
        format.json { render json: @squad, status: :created, location: @squad }
      else
        format.html { render action: "new" }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /squads/1
  # PUT /squads/1.json
  def update
    @squad = Squad.find(params[:id])

    respond_to do |format|
      if @squad.update_attributes(params[:squad])
        format.html { redirect_to @squad, notice: 'Squad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squads/1
  # DELETE /squads/1.json
  def destroy
    @squad = Squad.find(params[:id])
    @squad.destroy

    respond_to do |format|
      format.html { redirect_to squads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/_form.html.erb
<%= simple_form_for(@squad) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :weight %>
    <%= f.input :height %>
    <%= f.input :country, as: :string   %>
    <%= f.input :position %>
    <%= f.input :position_strg %>
    <%= f.input :group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/squads/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
         	  <li><%= link_to "Home", :home %></li>
			<li><%= link_to "Users", users_path %></li> 
	          <li><%= link_to "Squad Picks", matchpicks_path %></li>
	    		<li><%= link_to "Fixtures", fixtures_path %></li> 
						<li><%= link_to "Leaderboard", scoreboards_path %></li>
							<li><%= link_to "Rules", :rules	%><li>
								<li  class="active"><%= link_to "Admin", :admin %></li>
						
		
        </ul>
        <h3 class="muted">Lions Tour Predictascore</h3>
      </div>
   
      <hr>

app/views/squads/edit.html.erb
<h2>Edit squad</h2>

<%= render 'form' %>

<%= link_to 'Show', @squad %> |
<%= link_to 'Back', squads_path %>

app/views/squads/index.html.erb
<h3>Squad 2013</h3>

<ul class="nav nav-tabs">
  <li class="active">
   	<a href="/squads">Full Squad</a>
  </li>
  <li>	<a href="/squads/test1">1st Test</a></li>
   <li>	<a href="/squads/test2">2nd Test</a></li>
      <li>	<a href="/squads/test2">3rd Test</a></li>
</ul><br>

<div class="row-fluid">
  <div class="span6 offset1">
<% @squad_by_country.each do |country, squads| %>
<table class="table">
  <tr>
    <th>Name</th>
    <th><center>Stats</center></th>
    <% if signed_in? && current_user.admin? %>
    <th><center>Admin</center></th> <th><center>1st</center></th>  <th><center>2nd</center></th>   <th><center>3rd</center></th>
    <% end %>
  </tr>
<br><tr><h4 class="muted"><%= country %></h4></tr>
<% squads.each do |squad| %>
  <tr>
    <td><h6><%= squad.name %></h6>(<%= squad.position_strg %>)</td>
    <td><center><%= squad.age %>yrs <br><%= squad.weight %>kg <br><%= squad.height %>cms</td>
   
 <td><center><% if signed_in? && current_user.admin? %>	
	<%= link_to 'E', edit_squad_path(squad) %> : 
	<%= link_to 'D', squad, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
	<td><center><%= best_in_place squad, :test1, :type => :checkbox, collection: %w[No Yes] %></td>
	<td><center><%= best_in_place squad, :test2, :type => :checkbox, collection: %w[No Yes] %></td>
	<td><center><%= best_in_place squad, :test3, :type => :checkbox, collection: %w[No Yes] %></td>
	<% else %><% end %>
  </tr>
<% end %>
</table>
<% end %>
</div></div>
<br />
<br />
<br />
	<% if signed_in? && current_user.admin? %>
<div class="btn-group btn-group-vertical">
  <button class="btn btn-large"><%= link_to "Add squad member", new_squad_path, class: "btn btn-primary" %></button>
  <button class="btn">	<%= form_tag import_squads_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import" %>
	<% end %></button>
	<% end %>

app/views/squads/new.html.erb
<h2>New squad member</h2>

<%= render 'form' %>

<%= link_to 'Back', squads_path %>

app/views/squads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @squad.name %>
</p>

<p>
  <b>Age:</b>
  <%= @squad.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @squad.weight %>
</p>

<p>
  <b>Height:</b>
  <%= @squad.height %>
</p>

<p>
  <b>Country:</b>
  <%= @squad.country %>
</p>

<p>
  <b>Position:</b>
  <%= @squad.position %>
</p>

<p>
  <b>Position strg:</b>
  <%= @squad.position_strg %>
</p>

<p>
  <b>Group:</b>
  <%= @squad.group %>
</p>


<%= link_to 'Edit', edit_squad_path(@squad) %> |
<%= link_to 'Back', squads_path %>

app/views/squads/test1.html.erb
<h3>Squad 2013</h3>

<ul class="nav nav-tabs">
  <li>
   	<a href="/squads">Full Squad</a>
  </li>
  <li class="active">	<a href="/squads/test1">1st Test</a></li>
   <li>	<a href="/squads/test2">2nd Test</a></li>
      <li>	<a href="/squads/test3">3rd Test</a></li>
</ul><br>

<div class="row-fluid">
  <div class="span6 offset1">
  <% if @squads_test1.nil? %>
    Test Squad not yet announced<br>
    <% else %>

  
<% @squads_test1.each do |squad| %>
<ul>
    <li><%= squad.name %>  --  <%= squad.country %></li>

   </ul>
 
  </tr>
<% end %>
</table>
<% end %>
</div></div>
<br />

app/views/squads/test2.html.erb
<h3>Squad 2013</h3>

<ul class="nav nav-tabs">
  <li>
   	<a href="/squads">Full Squad</a>
  </li>
  <li>	<a href="/squads/test1">1st Test</a></li>
   <li class="active">	<a href="/squads/test2">2nd Test</a></li>
      <li>	<a href="/squads/test3">3rd Test</a></li>
</ul><br>

<div class="row-fluid">
  <div class="span6 offset1">
  <% if @squads_test2.nil? %>
    Test Squad not yet announced<br>
    <% else %>

  
<% @squads_test2.each do |squad| %>
<ul>
    <li><%= squad.name %>  --  <%= squad.country %></li>

   </ul>
 
  </tr>
<% end %>
</table>
<% end %>
</div></div>
<br />

app/views/squads/test3.html.erb
<h3>Squad 2013</h3>

<ul class="nav nav-tabs">
  <li>
   	<a href="/squads">Full Squad</a>
  </li>
  <li>	<a href="/squads/test1">1st Test</a></li>
   <li>	<a href="/squads/test2">2nd Test</a></li>
      <li class="active">	<a href="/squads/test3">3rd Test</a></li>
</ul><br>

<div class="row-fluid">
  <div class="span6 offset1">
  <% if @squads_test3.nil? %>
    Test Squad not yet announced<br>
    <% else %>

  
<% @squads_test3.each do |squad| %>
<ul>
    <li><%= squad.name %>  --  <%= squad.country %></li>

   </ul>
 
  </tr>
<% end %>
</table>
<% end %>
</div></div>
<br />